apiVersion: v1
kind: ReplicationController
metadata: 
  name: apache
  labels:
    nginx: rc
spec:
  replicas: 1
  selector: 
    name: apache
  template:
     metadata:
       labels:
         name: apache
     spec: 
       containers: 
       - name: apache
         image: httpd   
         #       ports:
         #  - containerPort: 80
---
apiVersion: v1
kind: Service
metadata: 
  name: apache
spec:
  selector:
    nginx: apache
  ports: 
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
