apiVersion: v1
kind: ReplicationController
metadata: 
  name: nginx-test
  labels:
    nginx: rc
spec:
  replicas: 1
  selector: 
    name: nginxsvc
  template:
     metadata:
       labels:
         name: nginxsvc
     spec: 
       containers: 
       - name: nginx-test
         image: nginx   
         #       ports:
         #  - containerPort: 80
---
apiVersion: v1
kind: Service
metadata: 
  name: nginx-svc
spec:
  selector:
    nginx: rc
  ports: 
  - protocol: TCP
    port: 80
  type: NodePort
